-- Migration pour insérer les ressources et leurs compétences
-- Note: Cette migration utilise des CTE pour gérer les insertions de manière optimale

BEGIN;

-- ===================================================================
-- 1. Insérer les ressources uniques (une seule ligne par NomPrenom)
-- ===================================================================
WITH ressources_data AS (
  SELECT DISTINCT ON (nom_prenom)
    nom_prenom,
    type_contrat,
    site,
    responsable,
    actif,
    date_fin
  FROM (VALUES
    ('ABARKAN Amin', 'APP', 'DAMPIERRE', 'FAUVELLE Julien', true, NULL),
    ('ABDELHAKK Mourad', 'CDI', 'DAMPIERRE', 'FAUVELLE Julien', true, NULL),
    ('ABELS Joanna', 'ETT', 'BLAYAIS', 'HECHT Mathieu', true, NULL),
    ('AKTAS Melih', 'ETT', 'BLAYAIS', 'HECHT Mathieu', true, NULL),
    ('APPELBAUM Vianney', 'CDI', 'BELLEVILLE', 'BARBEROT Matthieu', true, NULL),
    ('AUFRERE Didier', 'CDI', 'BELLEVILLE', 'BARBEROT Matthieu', true, NULL),
    ('BAMANA MADZOKO Ange', 'CDI', 'CHINON', 'NAIMI Laïd', true, NULL),
    ('BARBEROT Matthieu', 'CDI', 'SAVIGNY', 'LOIRAT Michel', true, NULL),
    ('BAUDRY Frédéric', 'CDI', 'SAVIGNY', 'BARBEROT Matthieu', true, NULL),
    ('BENOIST Numa', 'CDI', 'CHINON', 'NAIMI Laïd', true, NULL),
    ('BENSALEM Rafik', 'ETT', 'BLAYAIS', 'HECHT Mathieu', true, NULL),
    ('BERGEOT Marine', 'CDI', 'BLAYAIS', 'TOURNIER Antoine', true, NULL),
    ('BERTAULT Frédéric', 'CDI', 'CHINON', 'LECLERCQ Christophe', true, NULL),
    ('BERTHEAU Anthony', 'CDI', 'DAMPIERRE', 'FAUVELLE Julien', true, NULL),
    ('BERTHIER Marwin', 'CDI', 'DAMPIERRE', 'HEZZI Ridha', true, NULL),
    ('BERTHOUD Ludovic', 'CDI', 'BLAYAIS', 'HECHT Mathieu', true, NULL),
    ('BERTRAND Antoine', 'ETT', 'DAMPIERRE', 'FAUVELLE Julien', true, NULL),
    ('BLASCO Kévin', 'CDI', 'BLAYAIS', 'BERGEOT Marine', true, NULL),
    ('BOIS John', 'ETT', 'DAMPIERRE', 'FAUVELLE Julien', true, '2026-01-30'::date),
    ('BOISSEAU Pascal', 'CDI', 'CHINON', 'LECLERCQ Christophe', true, NULL),
    ('BONGIOVANNI F.', 'CDI', 'GOLFECH', 'CORRECH Christian', true, NULL),
    ('BOUAOUD KEVIN', 'CDI', 'BLAYAIS', 'BERGEOT Marine', true, NULL),
    ('BOULEDJOUDJA Nasser', 'CDI', 'BLAYAIS', 'HECHT Mathieu', true, NULL),
    ('BOULINEAU Damien', 'ETT', 'BLAYAIS', 'BERGEOT Marine', true, NULL),
    ('BOURDEAU Mathieu', 'CDI', 'SAVIGNY', 'DUPUY Alain', true, NULL),
    ('BOURIAL Rachid', 'CDI', 'BLAYAIS', 'HECHT Mathieu', true, NULL),
    ('BOUSSIKHANI Khalid', 'CDI', 'DAMPIERRE', 'FAUVELLE Julien', true, NULL),
    ('BOUVET THEO', 'CDI', 'BLAYAIS', 'LAFON Sébastien', true, NULL),
    ('BRUCY Eric', 'CDI', 'DAMPIERRE', 'FAUVELLE Julien', true, NULL),
    ('CADEAU Jérome', 'ETT', 'BLAYAIS', 'BERGEOT Marine', true, NULL),
    ('CARRE Steven', 'CDI', 'CHINON', 'LECLERCQ Christophe', true, NULL),
    ('CATEAU Alexandre', 'CDI', 'CHINON', 'LECLERCQ Christophe', true, NULL),
    ('CENSE Anthony', 'CDI', 'GOLFECH', 'CORRECH Christian', true, NULL),
    ('CHANTEREAU Yoann', 'CDI', 'DAMPIERRE', 'HEZZI Ridha', true, NULL),
    ('CHEVRIER Alain', 'CDI', 'GOLFECH', 'CORRECH Christian', true, NULL),
    ('CHIRINIAN Philippe', 'CDI', 'SAINT-LAURENT', 'LECLERCQ Christophe', true, NULL),
    ('CHOISY Matthieu', 'CDI', 'BELLEVILLE', 'BARBEROT Matthieu', true, NULL),
    ('CHUDEAU Quentin', 'CDI', 'CHINON', 'LECLERCQ Christophe', true, NULL),
    ('CLEMENT Lucas', 'CDI', 'DAMPIERRE', 'FAUVELLE Julien', true, NULL),
    ('COILLIOT Valentin', 'CDI', 'DAMPIERRE', 'FAUVELLE Julien', true, NULL),
    ('COLLAS Valentin', 'CDI', 'BLAYAIS', 'HECHT Mathieu', true, NULL),
    ('CORRECH Chrisitan', 'CDI', 'GOLFECH', 'TOURNIER Antoine', true, NULL),
    ('COUCHOURON Jean Christophe', 'CDI', 'SAVIGNY', 'LOIRAT Michel', true, NULL),
    ('COURVALET Sébastien', 'CDI', 'DAMPIERRE', 'FAUVELLE Julien', true, NULL),
    ('DAGOUNEAU Jimmy', 'CDI', 'BELLEVILLE', 'BARBEROT Matthieu', true, NULL),
    ('DANET Nicolas', 'CDI', 'GOLFECH', 'CORRECH Christian', true, NULL),
    ('DAVID Douglas', 'CDI', 'SAVIGNY', 'DUPUY Alain', true, NULL),
    ('DAVID Jordan', 'ETT', 'DAMPIERRE', 'FAUVELLE Julien', true, NULL),
    ('DEAGOSTINI Logan', 'CDI', 'BELLEVILLE', 'BARBEROT Matthieu', true, NULL),
    ('DEFORGES MICKAEL', 'CDI', 'BLAYAIS', 'BERGEOT Marine', true, NULL),
    ('DELABY Steven', 'CDI', 'CHINON', 'NAIMI Laïd', true, NULL),
    ('DELAIGUE Luc', 'ETT', 'BLAYAIS', 'BERGEOT Marine', true, NULL),
    ('DELNOMDEDIEU Yoann', 'CDI', 'BLAYAIS', 'LAFON Sébastien', true, NULL),
    ('DELORME CERISIER Cédric', 'CDI', 'BLAYAIS', 'BERGEOT Marine', true, NULL),
    ('DEMESTRE Steven', 'ETT', 'BLAYAIS', 'BERGEOT Marine', true, NULL),
    ('DEMICHELIS Thomas', 'ETT', 'BLAYAIS', 'BERGEOT Marine', true, NULL),
    ('DESCHAMPS Guillaume', 'CDI', 'BLAYAIS', 'HECHT Mathieu', true, NULL),
    ('DEVANNE Hubert', 'ETT', 'BLAYAIS', 'BERGEOT Marine', true, NULL),
    ('DEZE Erika', 'CDI', 'SAVIGNY', 'LOIRAT Michel', true, NULL),
    ('DIDIER Sullivan', 'ETT', 'BLAYAIS', 'HECHT Mathieu', true, NULL),
    ('DROUOT Vincent', 'CDI', 'BELLEVILLE', 'BARBEROT Matthieu', true, NULL),
    ('DUBOIS Nathan', 'ETT', 'BLAYAIS', 'HECHT Mathieu', true, NULL),
    ('DUMETZ Kévin', 'CDI', 'DAMPIERRE', 'FAUVELLE Julien', true, NULL),
    ('DUPUY Alain', 'CDI', 'SAVIGNY', 'LOIRAT Michel', true, NULL),
    ('DUTEMPLE Sullyvan', 'ETT', 'DAMPIERRE', 'FAUVELLE Julien', true, NULL),
    ('EDOLFI Didier', 'CDI', 'BLAYAIS', 'HECHT Mathieu', true, NULL),
    ('EL MOURABIT Saïd', 'CDI', 'DAMPIERRE', 'FAUVELLE Julien', true, NULL),
    ('ESCAFIT Bastien', 'CDI', 'GOLFECH', 'CORRECH Christian', true, NULL),
    ('FARJAUDOU Alexandra', 'ETT', 'DAMPIERRE', 'FAUVELLE Julien', true, NULL),
    ('FAUVELLE Julien', 'CDI', 'DAMPIERRE', 'BARBEROT Matthieu', true, NULL),
    ('FOLIARD Clement', 'CDI', 'CHINON', 'LECLERCQ Christophe', true, NULL),
    ('FONTAINE Tim', 'ETT', 'DAMPIERRE', 'FAUVELLE Julien', true, NULL),
    ('FOUBERT Enzo', 'ETT', 'DAMPIERRE', 'FAUVELLE Julien', true, NULL),
    ('FOUCHER Félicie', 'ETT', 'DAMPIERRE', 'FAUVELLE Julien', true, NULL),
    ('FOUCHER Melodie', 'CDI', 'DAMPIERRE', 'FAUVELLE Julien', true, NULL),
    ('FOULON Thomas', 'ETT', 'DAMPIERRE', 'FAUVELLE Julien', true, NULL),
    ('GALLET Arnaud', 'CDI', 'BLAYAIS', 'BERGEOT Marine', true, NULL),
    ('GARDERA Nicolas', 'CDI', 'DAMPIERRE', 'FAUVELLE Julien', true, NULL),
    ('GARDERA Richard', 'CDI', 'DAMPIERRE', 'FAUVELLE Julien', true, NULL),
    ('GERVIER Quentin', 'APP', 'SAVIGNY', 'DUPUY Alain', true, NULL),
    ('GIBEAU Matthis', 'ETT', 'BLAYAIS', 'BERGEOT Marine', true, NULL),
    ('GIUGLAR Jean-luc', 'ETT', 'BLAYAIS', 'HECHT Mathieu', true, NULL),
    ('GODINEAU André', 'CDI', 'CHINON', 'LECLERCQ Christophe', true, NULL),
    ('GRANDJEAN Maxime', 'CDI', 'DAMPIERRE', 'FAUVELLE Julien', true, NULL),
    ('GRATIA Jason', 'CDI', 'CHINON', 'LECLERCQ Christophe', true, NULL),
    ('GUILLET Nicolas', 'ETT', 'DAMPIERRE', 'FAUVELLE Julien', true, NULL),
    ('HAMMAMI Lotfi', 'CDI', 'DAMPIERRE', 'FAUVELLE Julien', true, NULL),
    ('HAMMI Sofiane', 'ETT', 'BLAYAIS', 'HECHT Mathieu', true, NULL),
    ('HECHT Mathieu', 'CDI', 'BLAYAIS', 'TOURNIER Antoine', true, NULL),
    ('HENUSET Kevin', 'CDI', 'DAMPIERRE', 'FAUVELLE Julien', true, NULL),
    ('HEU Tong', 'CDI', 'DAMPIERRE', 'FAUVELLE Julien', true, NULL),
    ('JARRY Yohann', 'CDI', 'BLAYAIS', 'HECHT Mathieu', true, NULL),
    ('JUCQUOIS Cyril', 'CDI', 'CHINON', 'LECLERCQ Christophe', true, NULL),
    ('KLIN Tony', 'CDI', 'BLAYAIS', 'BERGEOT Marine', true, NULL),
    ('LA VILLE Aurélia', 'CDI', 'BLAYAIS', 'LAFON Sébastien', true, NULL),
    ('LAFAGE Gabin', 'CDI', 'GOLFECH', 'CORRECH Christian', true, NULL),
    ('LAFON Olivier', 'CDI', 'BLAYAIS', 'LAFON Sébastien', true, NULL),
    ('LAFON Sébastien', 'CDI', 'BLAYAIS', 'HECHT Mathieu', true, NULL),
    ('LASALLE Laurent', 'CDI', 'BLAYAIS', 'HECHT Mathieu', true, NULL),
    ('LASSALLE Marie', 'CDI', 'BLAYAIS', 'LAFON Sébastien', true, NULL),
    ('LE CALVEZ Denis', 'CDI', 'BLAYAIS', 'HECHT Mathieu', true, NULL),
    ('LE COMPAS Vincent', 'CDI', 'CHINON', 'LECLERCQ Christophe', true, NULL),
    ('LEBEAU Christian', 'CDI', 'CHINON', 'LECLERCQ Christophe', true, NULL),
    ('LECLERCQ Christophe', 'CDI', 'SAVIGNY', 'LOIRAT Michel', true, NULL),
    ('LEDUC Dylan', 'CDI', 'DAMPIERRE', 'FAUVELLE Julien', true, NULL),
    ('LEGER Fabrice', 'CDI', 'BLAYAIS', 'HECHT Mathieu', true, NULL),
    ('LESIEUX Sidoine', 'CDI', 'BLAYAIS', 'LAFON Sébastien', true, NULL),
    ('LILA Papa Mor', 'CDI', 'DAMPIERRE', 'FAUVELLE Julien', true, NULL),
    ('LOIRAT Michel', 'CDI', 'SAVIGNY', 'LOIRAT Michel', true, NULL),
    ('LORENZO Guillaume', 'CDI', 'DAMPIERRE', 'FAUVELLE Julien', true, NULL),
    ('LY Eric', 'CDI', 'CHINON', 'LECLERCQ Christophe', true, NULL),
    ('LY Tsou Tchia', 'CDI', 'CHINON', 'LECLERCQ Christophe', true, NULL),
    ('MANDOT Angi', 'ETT', 'BLAYAIS', 'BERGEOT Marine', true, NULL),
    ('MANDOT Jason', 'ETT', 'BLAYAIS', 'BERGEOT Marine', true, NULL),
    ('MARCHET Stéphane', 'ETT', 'BLAYAIS', 'BERGEOT Marine', true, NULL),
    ('MARIN Léo', 'CDI', 'BLAYAIS', 'HECHT Mathieu', true, NULL),
    ('MARSEILLE Jean Philippe', 'CDI', 'DAMPIERRE', 'FAUVELLE Julien', true, NULL),
    ('MARTINS Nicolas', 'CDI', 'BLAYAIS', 'HECHT Mathieu', true, NULL),
    ('MASSAT Jean-Didier', 'CDI', 'GOLFECH', 'CORRECH Christian', true, NULL),
    ('MAYELE Oleo', 'ETT', 'BLAYAIS', 'HECHT Mathieu', true, NULL),
    ('MEFTAH Imed', 'CDI', 'BELLEVILLE', 'BARBEROT Matthieu', true, NULL),
    ('MEKKID Oualid', 'CDI', 'GOLFECH', 'CORRECH Christian', true, NULL),
    ('MENARD Adrien', 'CDI', 'CHINON', 'LECLERCQ Christophe', true, NULL),
    ('MENDES Armano', 'CDI', 'DAMPIERRE', 'FAUVELLE Julien', true, NULL),
    ('MENERO Tédy', 'CDI', 'GOLFECH', 'CORRECH Christian', true, NULL),
    ('MESSAOUDI Samir', 'ETT', 'BLAYAIS', 'HECHT Mathieu', true, NULL),
    ('MIEULET Franck', 'CDI', 'SAINT-LAURENT', 'LECLERCQ Christophe', true, NULL),
    ('MOREAU Benoit', 'CDI', 'DAMPIERRE', 'FAUVELLE Julien', true, NULL),
    ('MOREAU Joël', 'CDI', 'SAINT-LAURENT', 'LECLERCQ Christophe', true, NULL),
    ('MOTARD Frederic', 'CDI', 'BLAYAIS', 'HECHT Mathieu', true, NULL),
    ('MOUILLON Remy', 'CDI', 'CHINON', 'NAIMI Laïd', true, NULL),
    ('NAIMI Laïd', 'CDI', 'SAVIGNY', 'BARBEROT Matthieu', true, NULL),
    ('NDIAYE Cheikh', 'CDI', 'DAMPIERRE', 'FAUVELLE Julien', true, NULL),
    ('NERON Jean-francois', 'CDI', 'BLAYAIS', 'HECHT Mathieu', true, NULL),
    ('PACHNOPOULOS Naome', 'CDI', 'BLAYAIS', 'TOURNIER Antoine', true, NULL),
    ('PASDELOUP Joseph', 'CDI', 'DAMPIERRE', 'FAUVELLE Julien', true, NULL),
    ('PASQUIER Pascal', 'CDI', 'DAMPIERRE', 'FAUVELLE Julien', true, NULL),
    ('PASTRE Mathis', 'ETT', 'DAMPIERRE', 'FAUVELLE Julien', true, NULL),
    ('PATUREAU Tiffany', 'ETT', 'BLAYAIS', 'HECHT Mathieu', true, NULL),
    ('PENOT Robin', 'CDI', 'CHINON', 'LECLERCQ Christophe', true, NULL),
    ('PERRIN Julien', 'CDI', 'GOLFECH', 'CORRECH Christian', true, NULL),
    ('PERRIN Nathan', 'ETT', 'BLAYAIS', 'HECHT Mathieu', true, NULL),
    ('PESQUEREL Noémie', 'CDI', 'SAVIGNY', 'HEZZI Ridha', true, NULL),
    ('PETIT Sarah', 'ETT', 'SAVIGNY', 'LOIRAT Michel', true, NULL),
    ('PILLARD Alexandre', 'CDI', 'SAVIGNY', 'DUPUY Alain', true, NULL),
    ('PITAULT Christophe', 'CDI', 'DAMPIERRE', 'FAUVELLE Julien', true, NULL),
    ('POUSSE Charles', 'CDI', 'DAMPIERRE', 'FAUVELLE Julien', true, NULL),
    ('PRIEUR Claude -Henri', 'CDI', 'DAMPIERRE', 'FAUVELLE Julien', true, NULL),
    ('PRIMASE Valentin', 'CDI', 'BLAYAIS', 'BERGEOT Marine', true, NULL),
    ('PROUST Lucas', 'CDI', 'CHINON', 'LECLERCQ Christophe', true, NULL),
    ('RMILI Omar', 'CDI', 'BLAYAIS', 'HECHT Mathieu', true, NULL),
    ('ROBERT David', 'CDI', 'DAMPIERRE', 'FAUVELLE Julien', true, NULL),
    ('ROBINET Mickael', 'CDI', 'BLAYAIS', 'HECHT Mathieu', true, NULL),
    ('ROBLIN Julien', 'CDI', 'DAMPIERRE', 'FAUVELLE Julien', true, NULL),
    ('ROL Pascal', 'CDI', 'CHINON', 'LECLERCQ Christophe', true, NULL),
    ('ROULEAU Maxence', 'CDI', 'DAMPIERRE', 'FAUVELLE Julien', true, NULL),
    ('ROUZIES Julien', 'CDI', 'GOLFECH', 'CORRECH Christian', true, NULL),
    ('ROY Bernard', 'CDI', 'BLAYAIS', 'LAFON Sébastien', true, NULL),
    ('ROY Jean Francois', 'CDI', 'BELLEVILLE', 'BARBEROT Matthieu', true, NULL),
    ('ROY Maximilien', 'ETT', 'BLAYAIS', 'BERGEOT Marine', true, NULL),
    ('SALIN Florian', 'CDI', 'DAMPIERRE', 'BARBEROT Matthieu', true, NULL),
    ('SAVARY Guilhem', 'ETT', 'DAMPIERRE', 'FAUVELLE Julien', true, NULL),
    ('SEILLER Steven', 'CDI', 'DAMPIERRE', 'FAUVELLE Julien', true, NULL),
    ('SERPEBOIS Anis', 'ETT', 'BLAYAIS', 'HECHT Mathieu', true, NULL),
    ('SEVILLE Stephanie', 'CDI', 'CHINON', 'LECLERCQ Christophe', true, NULL),
    ('SISSOKO PECHON Lenny', 'CDI', 'SAINT-LAURENT', 'LECLERCQ Christophe', true, NULL),
    ('SLIMANI Kheireddine', 'CDI', 'BLAYAIS', 'HECHT Mathieu', true, NULL),
    ('STIEVENARD Paul', 'ETT', 'DAMPIERRE', 'FAUVELLE Julien', true, NULL),
    ('STOPYRA Françoise', 'CDI', 'SAVIGNY', 'LOIRAT Michel', true, NULL),
    ('TESSIER Nicolas', 'ETT', 'DAMPIERRE', 'FAUVELLE Julien', true, NULL),
    ('TESSIER Quentin', 'CDI', 'DAMPIERRE', 'FAUVELLE Julien', true, NULL),
    ('THAVENET Alain', 'CDI', 'BLAYAIS', 'HECHT Mathieu', true, NULL),
    ('THOR Jérome', 'CDI', 'DAMPIERRE', 'FAUVELLE Julien', true, NULL),
    ('TOULLEC Matthieu', 'CDI', 'BLAYAIS', 'HEZZI Ridha', true, NULL),
    ('TOURNIER Antoine', 'CDI', 'BLAYAIS', 'HECHT Mathieu', true, NULL),
    ('VANG Nou', 'CDI', 'DAMPIERRE', 'FAUVELLE Julien', true, NULL),
    ('VATAN Antonin', 'CDI', 'DAMPIERRE', 'FAUVELLE Julien', true, NULL),
    ('VERRON Denis', 'CDI', 'DAMPIERRE', 'FAUVELLE Julien', true, NULL),
    ('VIDEAU Vincent', 'CDI', 'BLAYAIS', 'BERGEOT Marine', true, NULL),
    ('VIGNALS Remy', 'ETT', 'BLAYAIS', 'HECHT Mathieu', true, NULL),
    ('WEPSIEC Elsa', 'CDI', 'SAVIGNY', 'HEZZI Ridha', true, NULL),
    ('XIONG Mathis', 'ETT', 'DAMPIERRE', 'FAUVELLE Julien', true, '2026-01-30'::date),
    ('ZANCHI Lény', 'CDI', 'BLAYAIS', 'HECHT Mathieu', true, NULL)
  ) AS t(nom_prenom, type_contrat, site, responsable, actif, date_fin)
  ORDER BY nom_prenom, type_contrat
),
ressources_inserted AS (
  INSERT INTO ressources (nom, site, type_contrat, responsable, actif, date_fin_contrat)
  SELECT 
    nom_prenom,
    site,
    type_contrat,
    responsable,
    actif,
    date_fin
  FROM ressources_data
  ON CONFLICT (nom, site) DO UPDATE SET
    type_contrat = EXCLUDED.type_contrat,
    responsable = EXCLUDED.responsable,
    actif = EXCLUDED.actif,
    date_fin_contrat = EXCLUDED.date_fin_contrat,
    updated_at = now()
  RETURNING id, nom
)

-- ===================================================================
-- 2. Insérer les compétences avec référence aux ressources
-- ===================================================================
INSERT INTO ressources_competences (ressource_id, competence, type_comp)
SELECT 
  r.id,
  comp_data.competence,
  comp_data.type_comp
FROM (
  VALUES
    ('ABARKAN Amin', 'DAMPIERRE', 'AUTO', 'P'),
    ('ABARKAN Amin', 'DAMPIERRE', 'IEG', 'S'),
    ('ABARKAN Amin', 'DAMPIERRE', 'PACK', 'S'),
    ('ABDELHAKK Mourad', 'DAMPIERRE', 'IEG', 'P'),
    ('ABELS Joanna', 'BLAYAIS', 'IEG', 'S'),
    ('ABELS Joanna', 'BLAYAIS', 'RELEVE', 'P'),
    ('AKTAS Melih', 'BLAYAIS', 'IEG', 'P'),
    ('APPELBAUM Vianney', 'BELLEVILLE', 'IEG', 'P'),
    ('AUFRERE Didier', 'BELLEVILLE', 'IEG', 'P'),
    ('AUFRERE Didier', 'BELLEVILLE', 'IES', 'S'),
    ('AUFRERE Didier', 'BELLEVILLE', 'INSTRUM', 'S'),
    ('AUFRERE Didier', 'BELLEVILLE', 'K1', 'S'),
    ('AUFRERE Didier', 'BELLEVILLE', 'RELEVE', 'S'),
    ('BAMANA MADZOKO Ange', 'CHINON', 'IES', 'P'),
    ('BAMANA MADZOKO Ange', 'CHINON', 'RELEVE', 'S'),
    ('BARBEROT Matthieu', 'SAVIGNY', 'BE_IES', 'S'),
    ('BARBEROT Matthieu', 'SAVIGNY', 'ENCADREMENT', 'P'),
    ('BARBEROT Matthieu', 'SAVIGNY', 'FIBRE OPTIQUE', 'S'),
    ('BAUDRY Frédéric', 'SAVIGNY', 'ENCADREMENT', 'P'),
    ('BAUDRY Frédéric', 'SAVIGNY', 'IEG', 'S'),
    ('BAUDRY Frédéric', 'SAVIGNY', 'PACK', 'S'),
    ('BAUDRY Frédéric', 'SAVIGNY', 'PREPA', 'S'),
    ('BAUDRY Frédéric', 'SAVIGNY', 'ESSAIS', 'S'),
    ('BAUDRY Frédéric', 'SAVIGNY', 'RELEVE', 'S'),
    ('BENOIST Numa', 'CHINON', 'ENCADREMENT', 'S'),
    ('BENOIST Numa', 'CHINON', 'IEG', 'S'),
    ('BENOIST Numa', 'CHINON', 'IES', 'P'),
    ('BENSALEM Rafik', 'BLAYAIS', 'IEG', 'P'),
    ('BERGEOT Marine', 'BLAYAIS', 'ENCADREMENT', 'P'),
    ('BERTAULT Frédéric', 'CHINON', 'TRACAGE', 'P'),
    ('BERTAULT Frédéric', 'CHINON', 'IEG', 'S'),
    ('BERTAULT Frédéric', 'CHINON', 'PACK', 'S'),
    ('BERTHEAU Anthony', 'DAMPIERRE', 'AUTO', 'S'),
    ('BERTHEAU Anthony', 'DAMPIERRE', 'PACK', 'P'),
    ('BERTHIER Marwin', 'DAMPIERRE', 'ADMIN', 'P'),
    ('BERTHOUD Ludovic', 'BLAYAIS', 'ROB', 'P'),
    ('BERTRAND Antoine', 'DAMPIERRE', 'IEG', 'P'),
    ('BLASCO Kévin', 'BLAYAIS', 'IEG', 'P'),
    ('BLASCO Kévin', 'BLAYAIS', 'RELEVE', 'S'),
    ('BOIS John', 'DAMPIERRE', 'IEG', 'P'),
    ('BOISSEAU Pascal', 'CHINON', 'IEG', 'P'),
    ('BONGIOVANNI F.', 'GOLFECH', 'ADMIN', 'P'),
    ('BOUAOUD KEVIN', 'BLAYAIS', 'IEG', 'P'),
    ('BOUAOUD KEVIN', 'BLAYAIS', 'RELEVE', 'S'),
    ('BOULEDJOUDJA Nasser', 'BLAYAIS', 'IEG', 'P'),
    ('BOULEDJOUDJA Nasser', 'BLAYAIS', 'K1', 'S'),
    ('BOULINEAU Damien', 'BLAYAIS', 'IEG', 'P'),
    ('BOURDEAU Mathieu', 'SAVIGNY', 'BE_IES', 'P'),
    ('BOURDEAU Mathieu', 'SAVIGNY', 'PREPA', 'S'),
    ('BOURIAL Rachid', 'BLAYAIS', 'IEG', 'P'),
    ('BOUSSIKHANI Khalid', 'DAMPIERRE', 'TRACAGE', 'S'),
    ('BOUSSIKHANI Khalid', 'DAMPIERRE', 'PACK', 'P'),
    ('BOUVET THEO', 'BLAYAIS', 'IEG', 'P'),
    ('BOUVET THEO', 'BLAYAIS', 'RELEVE', 'S'),
    ('BRUCY Eric', 'DAMPIERRE', 'IEG', 'P'),
    ('BRUCY Eric', 'DAMPIERRE', 'REDACTION_RA', 'S'),
    ('BRUCY Eric', 'DAMPIERRE', 'RELEVE', 'S'),
    ('CADEAU Jérome', 'BLAYAIS', 'IEG', 'P'),
    ('CARRE Steven', 'CHINON', 'INSTRUM', 'P'),
    ('CARRE Steven', 'CHINON', 'PREPA', 'S'),
    ('CATEAU Alexandre', 'CHINON', 'TRACAGE', 'P'),
    ('CATEAU Alexandre', 'CHINON', 'PACK', 'S'),
    ('CENSE Anthony', 'GOLFECH', 'IEG', 'P'),
    ('CENSE Anthony', 'GOLFECH', 'SS4', 'S'),
    ('CHANTEREAU Yoann', 'DAMPIERRE', 'HSE_CRP', 'P'),
    ('CHEVRIER Alain', 'GOLFECH', 'ENCADREMENT', 'S'),
    ('CHEVRIER Alain', 'GOLFECH', 'IEG', 'P'),
    ('CHEVRIER Alain', 'GOLFECH', 'SS4', 'S'),
    ('CHIRINIAN Philippe', 'SAINT-LAURENT', 'ENCADREMENT', 'P'),
    ('CHOISY Matthieu', 'BELLEVILLE', 'IEG', 'S'),
    ('CHOISY Matthieu', 'BELLEVILLE', 'PACK', 'P'),
    ('CHUDEAU Quentin', 'CHINON', 'ENCADREMENT', 'P'),
    ('CHUDEAU Quentin', 'CHINON', 'IEG', 'S'),
    ('CHUDEAU Quentin', 'CHINON', 'IES', 'S'),
    ('CHUDEAU Quentin', 'CHINON', 'PACK', 'S'),
    ('CHUDEAU Quentin', 'CHINON', 'PREPA', 'S'),
    ('CLEMENT Lucas', 'DAMPIERRE', 'IEG', 'P'),
    ('COILLIOT Valentin', 'DAMPIERRE', 'IEG', 'P'),
    ('COLLAS Valentin', 'BLAYAIS', 'MAGASIN', 'P'),
    ('CORRECH Chrisitan', 'GOLFECH', 'ENCADREMENT', 'P'),
    ('COUCHOURON Jean Christophe', 'SAVIGNY', 'MAGASIN', 'P'),
    ('COURVALET Sébastien', 'DAMPIERRE', 'IEG', 'S'),
    ('COURVALET Sébastien', 'DAMPIERRE', 'PACK', 'P'),
    ('DAGOUNEAU Jimmy', 'BELLEVILLE', 'AUTO', 'S'),
    ('DAGOUNEAU Jimmy', 'BELLEVILLE', 'ENCADREMENT', 'P'),
    ('DAGOUNEAU Jimmy', 'BELLEVILLE', 'IEG', 'S'),
    ('DAGOUNEAU Jimmy', 'BELLEVILLE', 'PACK', 'S'),
    ('DAGOUNEAU Jimmy', 'BELLEVILLE', 'K1', 'S'),
    ('DAGOUNEAU Jimmy', 'BELLEVILLE', 'ESSAIS', 'S'),
    ('DAGOUNEAU Jimmy', 'BELLEVILLE', 'RELEVE', 'S'),
    ('DANET Nicolas', 'GOLFECH', 'AUTO', 'S'),
    ('DANET Nicolas', 'GOLFECH', 'IEG', 'P'),
    ('DANET Nicolas', 'GOLFECH', 'PACK', 'S'),
    ('DANET Nicolas', 'GOLFECH', 'K1', 'S'),
    ('DANET Nicolas', 'GOLFECH', 'ESSAIS', 'S'),
    ('DAVID Douglas', 'SAVIGNY', 'BE_IES', 'P'),
    ('DAVID Douglas', 'SAVIGNY', 'PREPA', 'S'),
    ('DAVID Jordan', 'DAMPIERRE', 'IEG', 'S'),
    ('DAVID Jordan', 'DAMPIERRE', 'SS4', 'P'),
    ('DEAGOSTINI Logan', 'BELLEVILLE', 'AUTO', 'S'),
    ('DEAGOSTINI Logan', 'BELLEVILLE', 'IEG', 'S'),
    ('DEAGOSTINI Logan', 'BELLEVILLE', 'PACK', 'P'),
    ('DEAGOSTINI Logan', 'BELLEVILLE', 'K1', 'S'),
    ('DEFORGES MICKAEL', 'BLAYAIS', 'IEG', 'P'),
    ('DELABY Steven', 'CHINON', 'IES', 'P'),
    ('DELAIGUE Luc', 'BLAYAIS', 'AUTO', 'S'),
    ('DELAIGUE Luc', 'BLAYAIS', 'IEG', 'P'),
    ('DELNOMDEDIEU Yoann', 'BLAYAIS', 'MAGASIN', 'P'),
    ('DELORME CERISIER Cédric', 'BLAYAIS', 'IEG', 'P'),
    ('DEMESTRE Steven', 'BLAYAIS', 'IEG', 'P'),
    ('DEMICHELIS Thomas', 'BLAYAIS', 'IEG', 'P'),
    ('DESCHAMPS Guillaume', 'BLAYAIS', 'IEG', 'P'),
    ('DESCHAMPS Guillaume', 'BLAYAIS', 'RELEVE', 'S'),
    ('DEVANNE Hubert', 'BLAYAIS', 'IEG', 'P'),
    ('DEZE Erika', 'SAVIGNY', 'ADMIN', 'P'),
    ('DIDIER Sullivan', 'BLAYAIS', 'IEG', 'P'),
    ('DROUOT Vincent', 'BELLEVILLE', 'PREPA', 'P'),
    ('DUBOIS Nathan', 'BLAYAIS', 'IEG', 'P'),
    ('DUMETZ Kévin', 'DAMPIERRE', 'IEG', 'P'),
    ('DUPUY Alain', 'SAVIGNY', 'ENCADREMENT', 'P'),
    ('DUTEMPLE Sullyvan', 'DAMPIERRE', 'IEG', 'P'),
    ('EDOLFI Didier', 'BLAYAIS', 'IEG', 'P'),
    ('EDOLFI Didier', 'BLAYAIS', 'K1', 'S'),
    ('EL MOURABIT Saïd', 'DAMPIERRE', 'PACK', 'P'),
    ('ESCAFIT Bastien', 'GOLFECH', 'IEG', 'P'),
    ('FARJAUDOU Alexandra', 'DAMPIERRE', 'IEG', 'P'),
    ('FAUVELLE Julien', 'DAMPIERRE', 'ENCADREMENT', 'P'),
    ('FOLIARD Clement', 'CHINON', 'IES', 'S'),
    ('FOLIARD Clement', 'CHINON', 'INSTRUM', 'P'),
    ('FONTAINE Tim', 'DAMPIERRE', 'IEG', 'P'),
    ('FOUBERT Enzo', 'DAMPIERRE', 'IEG', 'P'),
    ('FOUCHER Félicie', 'DAMPIERRE', 'IEG', 'P'),
    ('FOUCHER Melodie', 'DAMPIERRE', 'PREPA', 'P'),
    ('FOULON Thomas', 'DAMPIERRE', 'IEG', 'S'),
    ('FOULON Thomas', 'DAMPIERRE', 'SS4', 'P'),
    ('GALLET Arnaud', 'BLAYAIS', 'ENCADREMENT', 'P'),
    ('GALLET Arnaud', 'BLAYAIS', 'IEG', 'S'),
    ('GALLET Arnaud', 'BLAYAIS', 'RELEVE', 'S'),
    ('GARDERA Nicolas', 'DAMPIERRE', 'IEG', 'P'),
    ('GARDERA Richard', 'DAMPIERRE', 'PACK', 'P'),
    ('GERVIER Quentin', 'SAVIGNY', 'BE_IES', 'P'),
    ('GERVIER Quentin', 'SAVIGNY', 'PREPA', 'S'),
    ('GIBEAU Matthis', 'BLAYAIS', 'IEG', 'P'),
    ('GIUGLAR Jean-luc', 'BLAYAIS', 'IEG', 'P'),
    ('GODINEAU André', 'CHINON', 'PACK', 'P'),
    ('GRANDJEAN Maxime', 'DAMPIERRE', 'PACK', 'P'),
    ('GRANDJEAN Maxime', 'DAMPIERRE', 'PREPA', 'S'),
    ('GRATIA Jason', 'CHINON', 'ENCADREMENT', 'P'),
    ('GRATIA Jason', 'CHINON', 'INSTRUM', 'S'),
    ('GUILLET Nicolas', 'DAMPIERRE', 'IEG', 'S'),
    ('GUILLET Nicolas', 'DAMPIERRE', 'PACK', 'P'),
    ('HAMMAMI Lotfi', 'DAMPIERRE', 'PACK', 'P'),
    ('HAMMI Sofiane', 'BLAYAIS', 'IEG', 'P'),
    ('HECHT Mathieu', 'BLAYAIS', 'ENCADREMENT', 'P'),
    ('HENUSET Kevin', 'DAMPIERRE', 'IEG', 'P'),
    ('HEU Tong', 'DAMPIERRE', 'IEG', 'P'),
    ('JARRY Yohann', 'BLAYAIS', 'IEG', 'P'),
    ('JUCQUOIS Cyril', 'CHINON', 'IEG', 'S'),
    ('JUCQUOIS Cyril', 'CHINON', 'IES', 'S'),
    ('JUCQUOIS Cyril', 'CHINON', 'PACK', 'P'),
    ('JUCQUOIS Cyril', 'CHINON', 'PREPA', 'S'),
    ('KLIN Tony', 'BLAYAIS', 'IEG', 'P'),
    ('LA VILLE Aurélia', 'BLAYAIS', 'SERVITUDE', 'P'),
    ('LA VILLE Aurélia', 'BLAYAIS', 'REDACTION_RA', 'S'),
    ('LAFAGE Gabin', 'GOLFECH', 'IEG', 'P'),
    ('LAFAGE Gabin', 'GOLFECH', 'SS4', 'S'),
    ('LAFON Olivier', 'BLAYAIS', 'IEG', 'P'),
    ('LAFON Olivier', 'BLAYAIS', 'RELEVE', 'S'),
    ('LAFON Sébastien', 'BLAYAIS', 'ENCADREMENT', 'P'),
    ('LAFON Sébastien', 'BLAYAIS', 'PREPA', 'S'),
    ('LASALLE Laurent', 'BLAYAIS', 'IEG', 'P'),
    ('LASALLE Laurent', 'BLAYAIS', 'RELEVE', 'S'),
    ('LASSALLE Marie', 'BLAYAIS', 'PREPA', 'S'),
    ('LASSALLE Marie', 'BLAYAIS', 'SERVITUDE', 'S'),
    ('LASSALLE Marie', 'BLAYAIS', 'REDACTION_RA', 'P'),
    ('LE CALVEZ Denis', 'BLAYAIS', 'IEG', 'S'),
    ('LE CALVEZ Denis', 'BLAYAIS', 'ESSAIS', 'P'),
    ('LE COMPAS Vincent', 'CHINON', 'IES', 'P'),
    ('LEBEAU Christian', 'CHINON', 'IEG', 'S'),
    ('LEBEAU Christian', 'CHINON', 'PACK', 'P'),
    ('LECLERCQ Christophe', 'SAVIGNY', 'ENCADREMENT', 'P'),
    ('LEDUC Dylan', 'DAMPIERRE', 'PACK', 'P'),
    ('LEGER Fabrice', 'BLAYAIS', 'ENCADREMENT', 'P'),
    ('LEGER Fabrice', 'BLAYAIS', 'IEG', 'S'),
    ('LEGER Fabrice', 'BLAYAIS', 'ESSAIS', 'S'),
    ('LESIEUX Sidoine', 'BLAYAIS', 'IEG', 'S'),
    ('LESIEUX Sidoine', 'BLAYAIS', 'RELEVE', 'P'),
    ('LILA Papa Mor', 'DAMPIERRE', 'IEG', 'P'),
    ('LOIRAT Michel', 'SAVIGNY', 'ENCADREMENT', 'P'),
    ('LORENZO Guillaume', 'DAMPIERRE', 'PACK', 'P'),
    ('LY Eric', 'CHINON', 'IES', 'S'),
    ('LY Eric', 'CHINON', 'PACK', 'P'),
    ('LY Eric', 'CHINON', 'FIBRE OPTIQUE', 'S'),
    ('LY Tsou Tchia', 'CHINON', 'IES', 'S'),
    ('LY Tsou Tchia', 'CHINON', 'PACK', 'P'),
    ('MANDOT Angi', 'BLAYAIS', 'IEG', 'P'),
    ('MANDOT Jason', 'BLAYAIS', 'IEG', 'P'),
    ('MARCHET Stéphane', 'BLAYAIS', 'IEG', 'P'),
    ('MARIN Léo', 'BLAYAIS', 'IEG', 'P'),
    ('MARSEILLE Jean Philippe', 'DAMPIERRE', 'PREPA', 'P'),
    ('MARTINS Nicolas', 'BLAYAIS', 'PREPA', 'P'),
    ('MASSAT Jean-Didier', 'GOLFECH', 'PREPA', 'P'),
    ('MAYELE Oleo', 'BLAYAIS', 'IEG', 'P'),
    ('MEFTAH Imed', 'BELLEVILLE', 'AUTO', 'S'),
    ('MEFTAH Imed', 'BELLEVILLE', 'IEG', 'P'),
    ('MEKKID Oualid', 'GOLFECH', 'IEG', 'P'),
    ('MEKKID Oualid', 'GOLFECH', 'ESSAIS', 'S'),
    ('MEKKID Oualid', 'GOLFECH', 'RELEVE', 'S'),
    ('MENARD Adrien', 'CHINON', 'IES', 'P'),
    ('MENDES Armano', 'DAMPIERRE', 'IEG', 'P'),
    ('MENERO Tédy', 'GOLFECH', 'IEG', 'P'),
    ('MESSAOUDI Samir', 'BLAYAIS', 'IEG', 'P'),
    ('MIEULET Franck', 'SAINT-LAURENT', 'IEG', 'S'),
    ('MIEULET Franck', 'SAINT-LAURENT', 'INSTRUM', 'S'),
    ('MIEULET Franck', 'SAINT-LAURENT', 'PACK', 'P'),
    ('MIEULET Franck', 'SAINT-LAURENT', 'FIBRE OPTIQUE', 'S'),
    ('MOREAU Benoit', 'DAMPIERRE', 'PACK', 'P'),
    ('MOREAU Joël', 'SAINT-LAURENT', 'TRACAGE', 'P'),
    ('MOTARD Frederic', 'BLAYAIS', 'IEG', 'S'),
    ('MOTARD Frederic', 'BLAYAIS', 'ESSAIS', 'P'),
    ('MOUILLON Remy', 'CHINON', 'IES', 'P'),
    ('NAIMI Laïd', 'SAVIGNY', 'ENCADREMENT', 'P'),
    ('NDIAYE Cheikh', 'DAMPIERRE', 'IEG', 'P'),
    ('NERON Jean-francois', 'BLAYAIS', 'AUTO', 'P'),
    ('NERON Jean-francois', 'BLAYAIS', 'IEG', 'S'),
    ('PACHNOPOULOS Naome', 'BLAYAIS', 'ADMIN', 'P'),
    ('PASDELOUP Joseph', 'DAMPIERRE', 'IEG', 'P'),
    ('PASQUIER Pascal', 'DAMPIERRE', 'IEG', 'P'),
    ('PASTRE Mathis', 'DAMPIERRE', 'IEG', 'P'),
    ('PATUREAU Tiffany', 'BLAYAIS', 'IEG', 'P'),
    ('PENOT Robin', 'CHINON', 'IEG', 'P'),
    ('PENOT Robin', 'CHINON', 'INSTRUM', 'S'),
    ('PERRIN Julien', 'GOLFECH', 'ENCADREMENT', 'P'),
    ('PERRIN Julien', 'GOLFECH', 'PREPA', 'S'),
    ('PERRIN Nathan', 'BLAYAIS', 'IEG', 'P'),
    ('PESQUEREL Noémie', 'SAVIGNY', 'ADMIN', 'P'),
    ('PETIT Sarah', 'SAVIGNY', 'ADMIN', 'P'),
    ('PILLARD Alexandre', 'SAVIGNY', 'BE_IES', 'P'),
    ('PILLARD Alexandre', 'SAVIGNY', 'PREPA', 'S'),
    ('PITAULT Christophe', 'DAMPIERRE', 'AUTO', 'P'),
    ('POUSSE Charles', 'DAMPIERRE', 'IEG', 'S'),
    ('POUSSE Charles', 'DAMPIERRE', 'SS4', 'P'),
    ('PRIEUR Claude -Henri', 'DAMPIERRE', 'PREPA', 'P'),
    ('PRIMASE Valentin', 'BLAYAIS', 'IEG', 'P'),
    ('PROUST Lucas', 'CHINON', 'IEG', 'S'),
    ('PROUST Lucas', 'CHINON', 'PACK', 'P'),
    ('RMILI Omar', 'BLAYAIS', 'IEG', 'P'),
    ('RMILI Omar', 'BLAYAIS', 'ESSAIS', 'S'),
    ('RMILI Omar', 'BLAYAIS', 'RELEVE', 'S'),
    ('ROBERT David', 'DAMPIERRE', 'IEG', 'P'),
    ('ROBINET Mickael', 'BLAYAIS', 'IEG', 'P'),
    ('ROBLIN Julien', 'DAMPIERRE', 'IEG', 'P'),
    ('ROL Pascal', 'CHINON', 'IEG', 'P'),
    ('ROL Pascal', 'CHINON', 'INSTRUM', 'S'),
    ('ROULEAU Maxence', 'DAMPIERRE', 'PREPA', 'P'),
    ('ROUZIES Julien', 'GOLFECH', 'PREPA', 'P'),
    ('ROUZIES Julien', 'GOLFECH', 'ESSAIS', 'S'),
    ('ROUZIES Julien', 'GOLFECH', 'RELEVE', 'S'),
    ('ROY Bernard', 'BLAYAIS', 'IEG', 'S'),
    ('ROY Bernard', 'BLAYAIS', 'RELEVE', 'P'),
    ('ROY Jean Francois', 'BELLEVILLE', 'AUTO', 'S'),
    ('ROY Jean Francois', 'BELLEVILLE', 'IEG', 'P'),
    ('ROY Jean Francois', 'BELLEVILLE', 'PACK', 'S'),
    ('ROY Jean Francois', 'BELLEVILLE', 'K1', 'S'),
    ('ROY Jean Francois', 'BELLEVILLE', 'RELEVE', 'S'),
    ('ROY Maximilien', 'BLAYAIS', 'IEG', 'P'),
    ('SALIN Florian', 'DAMPIERRE', 'ADMIN', 'P'),
    ('SAVARY Guilhem', 'DAMPIERRE', 'IEG', 'P'),
    ('SEILLER Steven', 'DAMPIERRE', 'AUTO', 'P'),
    ('SERPEBOIS Anis', 'BLAYAIS', 'IEG', 'P'),
    ('SEVILLE Stephanie', 'CHINON', 'IEG', 'S'),
    ('SEVILLE Stephanie', 'CHINON', 'IES', 'S'),
    ('SEVILLE Stephanie', 'CHINON', 'INSTRUM', 'S'),
    ('SEVILLE Stephanie', 'CHINON', 'PACK', 'S'),
    ('SEVILLE Stephanie', 'CHINON', 'FIBRE OPTIQUE', 'P'),
    ('SISSOKO PECHON Lenny', 'SAINT-LAURENT', 'TRACAGE', 'P'),
    ('SISSOKO PECHON Lenny', 'SAINT-LAURENT', 'PACK', 'S'),
    ('SLIMANI Kheireddine', 'BLAYAIS', 'IEG', 'P'),
    ('SLIMANI Kheireddine', 'BLAYAIS', 'ESSAIS', 'S'),
    ('SLIMANI Kheireddine', 'BLAYAIS', 'RELEVE', 'S'),
    ('STIEVENARD Paul', 'DAMPIERRE', 'IEG', 'P'),
    ('STOPYRA Françoise', 'SAVIGNY', 'ADMIN', 'P'),
    ('TESSIER Nicolas', 'DAMPIERRE', 'IES', 'P'),
    ('TESSIER Quentin', 'DAMPIERRE', 'IEG', 'P'),
    ('THAVENET Alain', 'BLAYAIS', 'IEG', 'P'),
    ('THAVENET Alain', 'BLAYAIS', 'RELEVE', 'S'),
    ('THOR Jérome', 'DAMPIERRE', 'PACK', 'P'),
    ('THOR Jérome', 'DAMPIERRE', 'PREPA', 'S'),
    ('TOULLEC Matthieu', 'BLAYAIS', 'HSE_CRP', 'P'),
    ('TOURNIER Antoine', 'BLAYAIS', 'ENCADREMENT', 'P'),
    ('VANG Nou', 'DAMPIERRE', 'PACK', 'P'),
    ('VATAN Antonin', 'DAMPIERRE', 'IEG', 'P'),
    ('VERRON Denis', 'DAMPIERRE', 'IEG', 'P'),
    ('VIDEAU Vincent', 'BLAYAIS', 'IEG', 'P'),
    ('VIGNALS Remy', 'BLAYAIS', 'IEG', 'P'),
    ('WEPSIEC Elsa', 'SAVIGNY', 'HSE_CRP', 'P'),
    ('XIONG Mathis', 'DAMPIERRE', 'IEG', 'P'),
    ('ZANCHI Lény', 'BLAYAIS', 'IEG', 'P')
) AS comp_data(nom_prenom, site, competence, type_comp)
INNER JOIN ressources_inserted r ON r.nom = comp_data.nom_prenom
ON CONFLICT DO NOTHING;

COMMIT;
